connect_db_params:
  dbname: myDataBase
  host: db
  password: '575980899598'
  port: 5432
  sslmode: disable
  user: alibazoubandi
connect_redis_params:
  addr: redis:6379
  password: ''
  db: 0
jwt:
  key: x6yvFsv4VNmzhm2biu-N_nkrJurBFfc9zHHs4YPHnnA=
server_address:
  host: 0.0.0.0
  port: 8080
