name: CD Pipeline

on:
  workflow_run:
    workflow: ["CI Pipeline"]
    type: [completed]

jobs:
  deploy:
    run-on: self-hosted

    steps:
      name: test local host runner
      run: |
        echo "we are just checking if we can run something on local machine"