name: Deploy to Local Machine

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner environment (can be any OS)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH connection
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key to GitHub Secrets

      # Step 3: Deploy to local machine
      - name: Deploy to local machine
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd D:\userManagementSystem 
          git fetch origin main     
          git reset --hard origin/main
          docker compose down
          docker compose up -d
          EOF