name: Deploy to Local Machine

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: self-hosted  # Run on your local Windows machine

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Navigate to the project folder and update the repository
      - name: Deploy on local Windows machine
        shell: pwsh
        run: |
          cd D:\userManagementSystem
          git fetch origin main
          git reset --hard origin/main
          docker compose down
          docker compose up -d
