name: CD Pipeline

on:
  workflow_run:
    workflows: [CI Pipeline]
    types:
      -completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Containers
        run: |
          docker compose up -d --build

      - name: Health Check
        run: |
          docker compose ps  # Check container status
          docker logs backend_container  # Print logs for debugging
