# This workflow will build a golang project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          version: "v0.1.15"
          # because we dont have secret key for codeconv for now we commented this
#          fail_ci_if_error: true

      # - name: Run security check
      #   run: |
      #     go install github.com/securego/gosec/v2/cmd/gosec@latest
      #     gosec ./...

#      - name: Run dependency check
#        run: |
#          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#          golangci-lint run --enable=goimports ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: my-backend-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker Compose
        run: |
          docker compose up -d --build
          sleep 30  # Wait for services to start
          docker compose ps  # Check container status

      - name: Health check
        run: |
          curl --retry 3 --retry-delay 5 --retry-connrefused http://localhost:8080/health || exit 1
